1) Use map to double each element in a list of numbers.
Use filter to select only the odd numbers from a list of integers.

In [2]:
import numpy as np
number_list = list(np.random.randint(11, size = 20))

def double(num):
    return num * 2

result = list(map(double, number_list))
print(result)

filtered = list(filter(lambda num: num %2 != 0, number_list))
print(filtered)

[16, 10, 6, 0, 8, 16, 6, 2, 4, 8, 16, 0, 12, 10, 14, 18, 10, 8, 4, 18]
[5, 3, 3, 1, 5, 7, 9, 5, 9]

2)Read a CSV file into a pandas DataFrame and display the first few rows. 
Group a DataFrame by a specific column and calculate the average of another column. 
Merge two DataFrames based on a common column.

In [7]:
import pandas as pd

df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
averages = df.Glucose.groupby(df.Outcome).mean()
print(averages)

Outcome
0    109.980000
1    141.257463
Name: Glucose, dtype: float64

In [7]:
df1 = pd.read_csv('dataframe1.csv')
df2 = pd.read_csv('dataframe2.csv')

df3 = df1.merge(df2, how = 'outer')
df3.head()

   ID   Name   Age      City Country
0   1   John  25.0  New York     USA
1   2  Alice  28.0    London      UK
2   3    Bob  32.0       NaN     NaN
3   4  Emily  30.0     Paris  France
4   5    NaN   NaN     Tokyo   Japan

3)Define a Person namedtuple with fields for name, age, and city. 
Create instances of Person and access their attributes.

In [8]:
from collections import namedtuple

Person = namedtuple('Person', ['name', 'age', 'city'])

person1 = Person('Alice', 26, 'London')
person2 = Person('Haru', 36, 'Seoul')

print(person1.name, person1.age, person1.city)
print(person2.name, person2.age, person2.city)

Alice 26 London
Haru 36 Seoul

4)Count the frequency of each word in a given text and display the top 5 most common words.
Merge two counters together and calculate the total count of each element.

In [1]:
# random text in article
text = """
Šis lengvas ir vasariškas desertas pagaminamas per penkias minutes. O po to tereikės tik 
sulaukti, kol atvės, ir mėgautis ne sąžinės graužimo, nes jis neriebus, ne per saldus ir labai gaivus. 
Tad puikiai tiks pasilepinti karštą vasaros dieną. Desertą galima ir netgi reikia pagaminti dieną prieš 
patiekiant, tad jis puikiai tinka laukiant svečių. Paruošus iš anksto, vienas darbas bus padarytas. 
Be to, desertas gaminamas atskiromis porcijomis, tad taip pat puikiai tinka vakarėliui. Jį galima 
gardinti bet kokiomis sezoninėmis uogomis, o jeigu norite, viršų apliekite spalvota žele. 
Kefyrinė panakota Reikės: 3 puodelių kefyro 1 puodelio pieno 3 arbatinio šaukštelio želatinos 
pusės stiklinės cukraus (ar pagal skonį) pusės arbatinio šaukštelio vanilės ekstrakto 
Mažame dubenyje užpilkite želatiną keliais šaukštais pieno. Leiskite pastovėti, kol išbrinks, apie 5 
minutes. Puode pašildykite pieną ir cukrų ant vidutinės ugnies, kol cukrus ištirps. 
Pienas turi būti karštas, bet neužvirti. Įmaišykite išbrinkusią želatiną, pakaitinkite, kol ištirps. 
Šiek tiek atvėsinkite ir supilkite kefyrą, išmaišykite. Supilstykite į indelius ir padėkite atvėsti. 
Kai visiškai atvės, dėkite į šaldytuvą ir šaldykite mažiausiai 3 valandas. Puoškite šviežiomis 
uogomis ir patiekite.
"""

In [4]:
#preprocessing the text
text_lower = text.lower()

for char in [',', '.', ':', '(', ')']:
    text_lower = text_lower.replace(char, '')

text_list = text_lower.split(' ')

new_word_list = [word.lstrip('\n').rstrip('\n') for word in text_list]
print(new_word_list)

['šis', 'lengvas', 'ir', 'vasariškas', 'desertas', 'pagaminamas', 'per', 'penkias', 'minutes', 'o', 'po', 'to', 'tereikės', 'tik', 'sulaukti', 'kol', 'atvės', 'ir', 'mėgautis', 'ne', 'sąžinės', 'graužimo', 'nes', 'jis', 'neriebus', 'ne', 'per', 'saldus', 'ir', 'labai', 'gaivus', 'tad', 'puikiai', 'tiks', 'pasilepinti', 'karštą', 'vasaros', 'dieną', 'desertą', 'galima', 'ir', 'netgi', 'reikia', 'pagaminti', 'dieną', 'prieš', 'patiekiant', 'tad', 'jis', 'puikiai', 'tinka', 'laukiant', 'svečių', 'paruošus', 'iš', 'anksto', 'vienas', 'darbas', 'bus', 'padarytas', 'be', 'to', 'desertas', 'gaminamas', 'atskiromis', 'porcijomis', 'tad', 'taip', 'pat', 'puikiai', 'tinka', 'vakarėliui', 'jį', 'galima', 'gardinti', 'bet', 'kokiomis', 'sezoninėmis', 'uogomis', 'o', 'jeigu', 'norite', 'viršų', 'apliekite', 'spalvota', 'žele', 'kefyrinė', 'panakota', 'reikės', '3', 'puodelių', 'kefyro', '1', 'puodelio', 'pieno', '3', 'arbatinio', 'šaukštelio', 'želatinos', 'pusės', 'stiklinės', 'cukraus', 'ar', 'pagal', 'skonį', 'pusės', 'arbatinio', 'šaukštelio', 'vanilės', 'ekstrakto', 'mažame', 'dubenyje', 'užpilkite', 'želatiną', 'keliais', 'šaukštais', 'pieno', 'leiskite', 'pastovėti', 'kol', 'išbrinks', 'apie', '5', 'minutes', 'puode', 'pašildykite', 'pieną', 'ir', 'cukrų', 'ant', 'vidutinės', 'ugnies', 'kol', 'cukrus', 'ištirps', 'pienas', 'turi', 'būti', 'karštas', 'bet', 'neužvirti', 'įmaišykite', 'išbrinkusią', 'želatiną', 'pakaitinkite', 'kol', 'ištirps', 'šiek', 'tiek', 'atvėsinkite', 'ir', 'supilkite', 'kefyrą', 'išmaišykite', 'supilstykite', 'į', 'indelius', 'ir', 'padėkite', 'atvėsti', 'kai', 'visiškai', 'atvės', 'dėkite', 'į', 'šaldytuvą', 'ir', 'šaldykite', 'mažiausiai', '3', 'valandas', 'puoškite', 'šviežiomis', 'uogomis', 'ir', 'patiekite']

In [8]:
from collections import Counter
c = Counter(new_word_list)
print(c)
print(c.most_common(5))

Counter({'ir': 9, 'kol': 4, 'tad': 3, 'puikiai': 3, '3': 3, 'desertas': 2, 'per': 2, 'minutes': 2, 'o': 2, 'to': 2, 'atvės': 2, 'ne': 2, 'jis': 2, 'dieną': 2, 'galima': 2, 'tinka': 2, 'bet': 2, 'uogomis': 2, 'pieno': 2, 'arbatinio': 2, 'šaukštelio': 2, 'pusės': 2, 'želatiną': 2, 'ištirps': 2, 'į': 2, 'šis': 1, 'lengvas': 1, 'vasariškas': 1, 'pagaminamas': 1, 'penkias': 1, 'po': 1, 'tereikės': 1, 'tik': 1, 'sulaukti': 1, 'mėgautis': 1, 'sąžinės': 1, 'graužimo': 1, 'nes': 1, 'neriebus': 1, 'saldus': 1, 'labai': 1, 'gaivus': 1, 'tiks': 1, 'pasilepinti': 1, 'karštą': 1, 'vasaros': 1, 'desertą': 1, 'netgi': 1, 'reikia': 1, 'pagaminti': 1, 'prieš': 1, 'patiekiant': 1, 'laukiant': 1, 'svečių': 1, 'paruošus': 1, 'iš': 1, 'anksto': 1, 'vienas': 1, 'darbas': 1, 'bus': 1, 'padarytas': 1, 'be': 1, 'gaminamas': 1, 'atskiromis': 1, 'porcijomis': 1, 'taip': 1, 'pat': 1, 'vakarėliui': 1, 'jį': 1, 'gardinti': 1, 'kokiomis': 1, 'sezoninėmis': 1, 'jeigu': 1, 'norite': 1, 'viršų': 1, 'apliekite': 1, 'spalvota': 1, 'žele': 1, 'kefyrinė': 1, 'panakota': 1, 'reikės': 1, 'puodelių': 1, 'kefyro': 1, '1': 1, 'puodelio': 1, 'želatinos': 1, 'stiklinės': 1, 'cukraus': 1, 'ar': 1, 'pagal': 1, 'skonį': 1, 'vanilės': 1, 'ekstrakto': 1, 'mažame': 1, 'dubenyje': 1, 'užpilkite': 1, 'keliais': 1, 'šaukštais': 1, 'leiskite': 1, 'pastovėti': 1, 'išbrinks': 1, 'apie': 1, '5': 1, 'puode': 1, 'pašildykite': 1, 'pieną': 1, 'cukrų': 1, 'ant': 1, 'vidutinės': 1, 'ugnies': 1, 'cukrus': 1, 'pienas': 1, 'turi': 1, 'būti': 1, 'karštas': 1, 'neužvirti': 1, 'įmaišykite': 1, 'išbrinkusią': 1, 'pakaitinkite': 1, 'šiek': 1, 'tiek': 1, 'atvėsinkite': 1, 'supilkite': 1, 'kefyrą': 1, 'išmaišykite': 1, 'supilstykite': 1, 'indelius': 1, 'padėkite': 1, 'atvėsti': 1, 'kai': 1, 'visiškai': 1, 'dėkite': 1, 'šaldytuvą': 1, 'šaldykite': 1, 'mažiausiai': 1, 'valandas': 1, 'puoškite': 1, 'šviežiomis': 1, 'patiekite': 1})
[('ir', 9), ('kol', 4), ('tad', 3), ('puikiai', 3), ('3', 3)]

In [7]:
#In this case there is only 1 counter, so I should create 
# a new one???

text2 = "man yra labai skanūs tortai pyragai su žele"
text2_list = text2.split(" ")
d = Counter(text2_list)
c.update(d)
print(c)

Counter({'ir': 9, 'kol': 4, 'tad': 3, 'puikiai': 3, '3': 3, 'desertas': 2, 'per': 2, 'minutes': 2, 'o': 2, 'to': 2, 'atvės': 2, 'ne': 2, 'jis': 2, 'labai': 2, 'dieną': 2, 'galima': 2, 'tinka': 2, 'bet': 2, 'uogomis': 2, 'žele': 2, 'pieno': 2, 'arbatinio': 2, 'šaukštelio': 2, 'pusės': 2, 'želatiną': 2, 'ištirps': 2, 'į': 2, 'šis': 1, 'lengvas': 1, 'vasariškas': 1, 'pagaminamas': 1, 'penkias': 1, 'po': 1, 'tereikės': 1, 'tik': 1, 'sulaukti': 1, 'mėgautis': 1, 'sąžinės': 1, 'graužimo': 1, 'nes': 1, 'neriebus': 1, 'saldus': 1, 'gaivus': 1, 'tiks': 1, 'pasilepinti': 1, 'karštą': 1, 'vasaros': 1, 'desertą': 1, 'netgi': 1, 'reikia': 1, 'pagaminti': 1, 'prieš': 1, 'patiekiant': 1, 'laukiant': 1, 'svečių': 1, 'paruošus': 1, 'iš': 1, 'anksto': 1, 'vienas': 1, 'darbas': 1, 'bus': 1, 'padarytas': 1, 'be': 1, 'gaminamas': 1, 'atskiromis': 1, 'porcijomis': 1, 'taip': 1, 'pat': 1, 'vakarėliui': 1, 'jį': 1, 'gardinti': 1, 'kokiomis': 1, 'sezoninėmis': 1, 'jeigu': 1, 'norite': 1, 'viršų': 1, 'apliekite': 1, 'spalvota': 1, 'kefyrinė': 1, 'panakota': 1, 'reikės': 1, 'puodelių': 1, 'kefyro': 1, '1': 1, 'puodelio': 1, 'želatinos': 1, 'stiklinės': 1, 'cukraus': 1, 'ar': 1, 'pagal': 1, 'skonį': 1, 'vanilės': 1, 'ekstrakto': 1, 'mažame': 1, 'dubenyje': 1, 'užpilkite': 1, 'keliais': 1, 'šaukštais': 1, 'leiskite': 1, 'pastovėti': 1, 'išbrinks': 1, 'apie': 1, '5': 1, 'puode': 1, 'pašildykite': 1, 'pieną': 1, 'cukrų': 1, 'ant': 1, 'vidutinės': 1, 'ugnies': 1, 'cukrus': 1, 'pienas': 1, 'turi': 1, 'būti': 1, 'karštas': 1, 'neužvirti': 1, 'įmaišykite': 1, 'išbrinkusią': 1, 'pakaitinkite': 1, 'šiek': 1, 'tiek': 1, 'atvėsinkite': 1, 'supilkite': 1, 'kefyrą': 1, 'išmaišykite': 1, 'supilstykite': 1, 'indelius': 1, 'padėkite': 1, 'atvėsti': 1, 'kai': 1, 'visiškai': 1, 'dėkite': 1, 'šaldytuvą': 1, 'šaldykite': 1, 'mažiausiai': 1, 'valandas': 1, 'puoškite': 1, 'šviežiomis': 1, 'patiekite': 1, 'man': 1, 'yra': 1, 'skanūs': 1, 'tortai': 1, 'pyragai': 1, 'su': 1})

5)Use a deque to implement a queue and perform enqueue and dequeue operations. Reverse the order of elements in a deque.

In [11]:
from collections import deque

queue = deque()

queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)

print("Queue:", queue)

item = queue.popleft()
print("Dequeued:", item)

item = queue.popleft()
print("Dequeued:", item)

print("Queue after dequeue:", queue)

queue.reverse()
print("Reversed Queue:", queue)

Queue: deque([1, 2, 3, 4])
Dequeued: 1
Dequeued: 2
Queue after dequeue: deque([3, 4])
Reversed Queue: deque([4, 3])

6)Create a defaultdict that maps a character to a list of words starting with that character. Calculate the sum of values for each key in a dictionary using a defaultdict.

In [13]:
from collections import defaultdict

words = ["apple", "zebra", "cupid", "school", "angel", "banana", "cat", "dog", "elephant", "frog"]

word_dict = defaultdict(list)

for word in words:
    word_dict[word[0]].append(word)

for key, value in word_dict.items():
    print(f"Words starting with '{key}': {value}")
    print(f"Total number of words starting with '{key}': {len(value)}")

Words starting with 'a': ['apple', 'angel']
Total number of words starting with 'a': 2
Words starting with 'z': ['zebra']
Total number of words starting with 'z': 1
Words starting with 'c': ['cupid', 'cat']
Total number of words starting with 'c': 2
Words starting with 's': ['school']
Total number of words starting with 's': 1
Words starting with 'b': ['banana']
Total number of words starting with 'b': 1
Words starting with 'd': ['dog']
Total number of words starting with 'd': 1
Words starting with 'e': ['elephant']
Total number of words starting with 'e': 1
Words starting with 'f': ['frog']
Total number of words starting with 'f': 1

7)Use reduce to find the maximum element in a list of numbers. Combine a list of strings into a single string using reduce.

In [3]:
from functools import reduce

def bigger(a, b):
    return a if a > b else b

numbers = [123, 54, 678, 999, 1, 15, 1001, 67]

maximum = reduce(bigger, numbers)
print(maximum)

1001

In [6]:
strings = ['bgdfdhd', 'cgweuyegcu', 'sksgwwrtwqn', 'dsbhsafdqyte']

def add(a, b):
    return a+b
    
summ = reduce(add, strings)
print(summ)

bgdfdhdcgweuyegcusksgwwrtwqndsbhsafdqyte

# Databases (SQL)

1) Select any free API (the choice is up to you, you can use any from https://rapidapi.com/collection/list-of-free-apis).

I chose Lithuanian weather api https://api.meteo.lt/v1

2) Create the database which stores the information related to the API chosen (at least 2 tables).

Created in mysql

3) In Python, 
3.1) implement the logic which fetches the data from API and moves it to Database 
3.2) Fetches the data from database and 
     3.2.1) If there is the API functionality (POST/GET request) which allows you to  use the data from database in an API call, do it 
     3.2.2) If not - display the data from database as Pandas dataframe

In [1]:
import requests

# observations of the last 24 hours in Vilnius
response = requests.get("https://api.meteo.lt/v1/stations/vilniaus-ams/observations/latest")
data = response.json()

In [2]:
data

{'station': {'code': 'vilniaus-ams',
  'name': 'Vilniaus AMS',
  'coordinates': {'latitude': 54.625992, 'longitude': 25.107064}},
 'observations': [{'observationTimeUtc': '2023-06-25 15:00:00',
   'airTemperature': 24.5,
   'feelsLikeTemperature': 24,
   'windSpeed': 3.2,
   'windGust': 6.4,
   'windDirection': 309,
   'cloudCover': 75,
   'seaLevelPressure': 1014.9,
   'relativeHumidity': 37,
   'precipitation': 0,
   'conditionCode': 'cloudy-with-sunny-intervals'},
  {'observationTimeUtc': '2023-06-25 16:00:00',
   'airTemperature': 20.4,
   'feelsLikeTemperature': 20.4,
   'windSpeed': 4.7,
   'windGust': 9.9,
   'windDirection': 318,
   'cloudCover': 100,
   'seaLevelPressure': 1015.9,
   'relativeHumidity': 49,
   'precipitation': 0,
   'conditionCode': 'cloudy'},
  {'observationTimeUtc': '2023-06-25 17:00:00',
   'airTemperature': 15.8,
   'feelsLikeTemperature': 15.8,
   'windSpeed': 1.8,
   'windGust': 4.2,
   'windDirection': 342,
   'cloudCover': 100,
   'seaLevelPressure': 1016.2,
   'relativeHumidity': 86,
   'precipitation': 1.3,
   'conditionCode': 'light-rain'},
  {'observationTimeUtc': '2023-06-25 18:00:00',
   'airTemperature': 16.1,
   'feelsLikeTemperature': 16.1,
   'windSpeed': 3.2,
   'windGust': 6.2,
   'windDirection': 303,
   'cloudCover': 88,
   'seaLevelPressure': 1016.4,
   'relativeHumidity': 84,
   'precipitation': 0.1,
   'conditionCode': 'rain'},
  {'observationTimeUtc': '2023-06-25 19:00:00',
   'airTemperature': 15.6,
   'feelsLikeTemperature': 15.6,
   'windSpeed': 0.9,
   'windGust': 2,
   'windDirection': 145,
   'cloudCover': 100,
   'seaLevelPressure': 1015.6,
   'relativeHumidity': 86,
   'precipitation': 0.1,
   'conditionCode': 'light-rain'},
  {'observationTimeUtc': '2023-06-25 20:00:00',
   'airTemperature': 14.4,
   'feelsLikeTemperature': 14.4,
   'windSpeed': 0.7,
   'windGust': 1.7,
   'windDirection': 234,
   'cloudCover': 75,
   'seaLevelPressure': 1015.6,
   'relativeHumidity': 93,
   'precipitation': 0,
   'conditionCode': 'cloudy-with-sunny-intervals'},
  {'observationTimeUtc': '2023-06-25 21:00:00',
   'airTemperature': 13.5,
   'feelsLikeTemperature': 13.5,
   'windSpeed': 1.4,
   'windGust': 2.2,
   'windDirection': 278,
   'cloudCover': 0,
   'seaLevelPressure': 1015.7,
   'relativeHumidity': 95,
   'precipitation': 0,
   'conditionCode': 'clear'},
  {'observationTimeUtc': '2023-06-25 22:00:00',
   'airTemperature': 12.6,
   'feelsLikeTemperature': 12.6,
   'windSpeed': 0.5,
   'windGust': 0.8,
   'windDirection': 329,
   'cloudCover': 75,
   'seaLevelPressure': 1015.7,
   'relativeHumidity': 96,
   'precipitation': 0,
   'conditionCode': 'cloudy-with-sunny-intervals'},
  {'observationTimeUtc': '2023-06-25 23:00:00',
   'airTemperature': 12.5,
   'feelsLikeTemperature': 12.5,
   'windSpeed': 1.5,
   'windGust': 2.5,
   'windDirection': 338,
   'cloudCover': 63,
   'seaLevelPressure': 1015.5,
   'relativeHumidity': 97,
   'precipitation': 0,
   'conditionCode': 'cloudy-with-sunny-intervals'},
  {'observationTimeUtc': '2023-06-26 00:00:00',
   'airTemperature': 12,
   'feelsLikeTemperature': 12,
   'windSpeed': 0.9,
   'windGust': 1.4,
   'windDirection': 331,
   'cloudCover': 0,
   'seaLevelPressure': 1015.5,
   'relativeHumidity': 96,
   'precipitation': 0,
   'conditionCode': 'mist'},
  {'observationTimeUtc': '2023-06-26 01:00:00',
   'airTemperature': 11.4,
   'feelsLikeTemperature': 11.4,
   'windSpeed': 0.5,
   'windGust': 0.7,
   'windDirection': 18,
   'cloudCover': 0,
   'seaLevelPressure': 1015.3,
   'relativeHumidity': 97,
   'precipitation': 0,
   'conditionCode': 'mist'},
  {'observationTimeUtc': '2023-06-26 02:00:00',
   'airTemperature': 10.8,
   'feelsLikeTemperature': 10.8,
   'windSpeed': 0.2,
   'windGust': 0.4,
   'windDirection': 105,
   'cloudCover': 38,
   'seaLevelPressure': 1015,
   'relativeHumidity': 97,
   'precipitation': 0,
   'conditionCode': 'fog'},
  {'observationTimeUtc': '2023-06-26 03:00:00',
   'airTemperature': 11.1,
   'feelsLikeTemperature': 11.1,
   'windSpeed': 0.8,
   'windGust': 1.1,
   'windDirection': 201,
   'cloudCover': 38,
   'seaLevelPressure': 1014.7,
   'relativeHumidity': 97,
   'precipitation': 0,
   'conditionCode': 'fog'},
  {'observationTimeUtc': '2023-06-26 04:00:00',
   'airTemperature': 14,
   'feelsLikeTemperature': 14,
   'windSpeed': 1,
   'windGust': 1.7,
   'windDirection': 97,
   'cloudCover': 88,
   'seaLevelPressure': 1014.4,
   'relativeHumidity': 93,
   'precipitation': 0,
   'conditionCode': 'cloudy'},
  {'observationTimeUtc': '2023-06-26 05:00:00',
   'airTemperature': 15.6,
   'feelsLikeTemperature': 15.6,
   'windSpeed': 0.8,
   'windGust': 1.5,
   'windDirection': 189,
   'cloudCover': 88,
   'seaLevelPressure': 1014.2,
   'relativeHumidity': 86,
   'precipitation': 0,
   'conditionCode': 'cloudy'},
  {'observationTimeUtc': '2023-06-26 06:00:00',
   'airTemperature': 15.5,
   'feelsLikeTemperature': 15.5,
   'windSpeed': 1.6,
   'windGust': 2.7,
   'windDirection': 86,
   'cloudCover': 50,
   'seaLevelPressure': 1013.9,
   'relativeHumidity': 89,
   'precipitation': 0,
   'conditionCode': 'variable-cloudiness'},
  {'observationTimeUtc': '2023-06-26 07:00:00',
   'airTemperature': 18.2,
   'feelsLikeTemperature': 18.2,
   'windSpeed': 0.9,
   'windGust': 2.3,
   'windDirection': 347,
   'cloudCover': 25,
   'seaLevelPressure': 1013.7,
   'relativeHumidity': 74,
   'precipitation': 0,
   'conditionCode': 'partly-cloudy'},
  {'observationTimeUtc': '2023-06-26 08:00:00',
   'airTemperature': 20.2,
   'feelsLikeTemperature': 20.2,
   'windSpeed': 1.9,
   'windGust': 3.8,
   'windDirection': 8,
   'cloudCover': 0,
   'seaLevelPressure': 1013.2,
   'relativeHumidity': 54,
   'precipitation': 0,
   'conditionCode': 'clear'},
  {'observationTimeUtc': '2023-06-26 09:00:00',
   'airTemperature': 20.8,
   'feelsLikeTemperature': 20.8,
   'windSpeed': 2.2,
   'windGust': 4.4,
   'windDirection': 3,
   'cloudCover': 38,
   'seaLevelPressure': 1012.9,
   'relativeHumidity': 55,
   'precipitation': 0,
   'conditionCode': 'variable-cloudiness'},
  {'observationTimeUtc': '2023-06-26 10:00:00',
   'airTemperature': 22.2,
   'feelsLikeTemperature': 22.2,
   'windSpeed': 1.8,
   'windGust': 4.7,
   'windDirection': 328,
   'cloudCover': 13,
   'seaLevelPressure': 1012.2,
   'relativeHumidity': 46,
   'precipitation': 0,
   'conditionCode': 'partly-cloudy'},
  {'observationTimeUtc': '2023-06-26 11:00:00',
   'airTemperature': 23.8,
   'feelsLikeTemperature': 23.3,
   'windSpeed': 2.7,
   'windGust': 5,
   'windDirection': 305,
   'cloudCover': 38,
   'seaLevelPressure': 1011.9,
   'relativeHumidity': 40,
   'precipitation': 0,
   'conditionCode': 'variable-cloudiness'},
  {'observationTimeUtc': '2023-06-26 12:00:00',
   'airTemperature': 20.1,
   'feelsLikeTemperature': 20.1,
   'windSpeed': 2.5,
   'windGust': 4.7,
   'windDirection': 10,
   'cloudCover': 50,
   'seaLevelPressure': 1012.1,
   'relativeHumidity': 59,
   'precipitation': 0,
   'conditionCode': 'rain-showers'},
  {'observationTimeUtc': '2023-06-26 13:00:00',
   'airTemperature': 22.6,
   'feelsLikeTemperature': 22.6,
   'windSpeed': 2.3,
   'windGust': 5.2,
   'windDirection': 10,
   'cloudCover': 13,
   'seaLevelPressure': 1011.7,
   'relativeHumidity': 45,
   'precipitation': 0,
   'conditionCode': 'partly-cloudy'},
  {'observationTimeUtc': '2023-06-26 14:00:00',
   'airTemperature': 21.3,
   'feelsLikeTemperature': 21.3,
   'windSpeed': 4.3,
   'windGust': 7.2,
   'windDirection': 303,
   'cloudCover': 88,
   'seaLevelPressure': 1011.6,
   'relativeHumidity': 53,
   'precipitation': 0.1,
   'conditionCode': 'rain'}]}

In [3]:
station_code = data['station']['code']
station_name = data['station']['name']
observations = data['observations']

In [4]:
import pandas as pd
df = pd.DataFrame(observations)

In [5]:
df

,observationTimeUtc,airTemperature,feelsLikeTemperature,windSpeed,windGust,windDirection,cloudCover,seaLevelPressure,relativeHumidity,precipitation,conditionCode
0,2023-06-25 15:00:00,24.5,24.0,3.2,6.4,309,75,1014.9,37,0.0,cloudy-with-sunny-intervals
1,2023-06-25 16:00:00,20.4,20.4,4.7,9.9,318,100,1015.9,49,0.0,cloudy
2,2023-06-25 17:00:00,15.8,15.8,1.8,4.2,342,100,1016.2,86,1.3,light-rain
3,2023-06-25 18:00:00,16.1,16.1,3.2,6.2,303,88,1016.4,84,0.1,rain
4,2023-06-25 19:00:00,15.6,15.6,0.9,2.0,145,100,1015.6,86,0.1,light-rain
5,2023-06-25 20:00:00,14.4,14.4,0.7,1.7,234,75,1015.6,93,0.0,cloudy-with-sunny-intervals
6,2023-06-25 21:00:00,13.5,13.5,1.4,2.2,278,0,1015.7,95,0.0,clear
7,2023-06-25 22:00:00,12.6,12.6,0.5,0.8,329,75,1015.7,96,0.0,cloudy-with-sunny-intervals
8,2023-06-25 23:00:00,12.5,12.5,1.5,2.5,338,63,1015.5,97,0.0,cloudy-with-sunny-intervals
9,2023-06-26 00:00:00,12.0,12.0,0.9,1.4,331,0,1015.5,96,0.0,mist
10,2023-06-26 01:00:00,11.4,11.4,0.5,0.7,18,0,1015.3,97,0.0,mist
11,2023-06-26 02:00:00,10.8,10.8,0.2,0.4,105,38,1015.0,97,0.0,fog
12,2023-06-26 03:00:00,11.1,11.1,0.8,1.1,201,38,1014.7,97,0.0,fog
13,2023-06-26 04:00:00,14.0,14.0,1.0,1.7,97,88,1014.4,93,0.0,cloudy
14,2023-06-26 05:00:00,15.6,15.6,0.8,1.5,189,88,1014.2,86,0.0,cloudy
15,2023-06-26 06:00:00,15.5,15.5,1.6,2.7,86,50,1013.9,89,0.0,variable-cloudiness
16,2023-06-26 07:00:00,18.2,18.2,0.9,2.3,347,25,1013.7,74,0.0,partly-cloudy
17,2023-06-26 08:00:00,20.2,20.2,1.9,3.8,8,0,1013.2,54,0.0,clear
18,2023-06-26 09:00:00,20.8,20.8,2.2,4.4,3,38,1012.9,55,0.0,variable-cloudiness
19,2023-06-26 10:00:00,22.2,22.2,1.8,4.7,328,13,1012.2,46,0.0,partly-cloudy
20,2023-06-26 11:00:00,23.8,23.3,2.7,5.0,305,38,1011.9,40,0.0,variable-cloudiness
21,2023-06-26 12:00:00,20.1,20.1,2.5,4.7,10,50,1012.1,59,0.0,rain-showers
22,2023-06-26 13:00:00,22.6,22.6,2.3,5.2,10,13,1011.7,45,0.0,partly-cloudy
23,2023-06-26 14:00:00,21.3,21.3,4.3,7.2,303,88,1011.6,53,0.1,rain

In [10]:
condition = list(df['conditionCode'])
conset = list(set(condition))
condition_df = pd.DataFrame(conset)
condition_df.columns = ['conditionCode']
condition_df = condition_df.rename_axis('id')
condition_df = condition_df.reset_index()

In [23]:
from sqlalchemy import create_engine
from sqlalchemy import text

engine = create_engine("mysql+pymysql://root:@localhost/bootcamp")
condition_df.to_sql(name="weather_conditions",con=engine,if_exists="append",index = False)

10

In [11]:
merged = pd.merge(df, condition_df, on = 'conditionCode', how = 'left')

,observationTimeUtc,airTemperature,feelsLikeTemperature,windSpeed,windGust,windDirection,cloudCover,seaLevelPressure,relativeHumidity,precipitation,conditionCode,id
0,2023-06-25 15:00:00,24.5,24.0,3.2,6.4,309,75,1014.9,37,0.0,cloudy-with-sunny-intervals,0
1,2023-06-25 16:00:00,20.4,20.4,4.7,9.9,318,100,1015.9,49,0.0,cloudy,6
2,2023-06-25 17:00:00,15.8,15.8,1.8,4.2,342,100,1016.2,86,1.3,light-rain,9
3,2023-06-25 18:00:00,16.1,16.1,3.2,6.2,303,88,1016.4,84,0.1,rain,1
4,2023-06-25 19:00:00,15.6,15.6,0.9,2.0,145,100,1015.6,86,0.1,light-rain,9
5,2023-06-25 20:00:00,14.4,14.4,0.7,1.7,234,75,1015.6,93,0.0,cloudy-with-sunny-intervals,0
6,2023-06-25 21:00:00,13.5,13.5,1.4,2.2,278,0,1015.7,95,0.0,clear,3
7,2023-06-25 22:00:00,12.6,12.6,0.5,0.8,329,75,1015.7,96,0.0,cloudy-with-sunny-intervals,0
8,2023-06-25 23:00:00,12.5,12.5,1.5,2.5,338,63,1015.5,97,0.0,cloudy-with-sunny-intervals,0
9,2023-06-26 00:00:00,12.0,12.0,0.9,1.4,331,0,1015.5,96,0.0,mist,2
10,2023-06-26 01:00:00,11.4,11.4,0.5,0.7,18,0,1015.3,97,0.0,mist,2
11,2023-06-26 02:00:00,10.8,10.8,0.2,0.4,105,38,1015.0,97,0.0,fog,4
12,2023-06-26 03:00:00,11.1,11.1,0.8,1.1,201,38,1014.7,97,0.0,fog,4
13,2023-06-26 04:00:00,14.0,14.0,1.0,1.7,97,88,1014.4,93,0.0,cloudy,6
14,2023-06-26 05:00:00,15.6,15.6,0.8,1.5,189,88,1014.2,86,0.0,cloudy,6
15,2023-06-26 06:00:00,15.5,15.5,1.6,2.7,86,50,1013.9,89,0.0,variable-cloudiness,8
16,2023-06-26 07:00:00,18.2,18.2,0.9,2.3,347,25,1013.7,74,0.0,partly-cloudy,5
17,2023-06-26 08:00:00,20.2,20.2,1.9,3.8,8,0,1013.2,54,0.0,clear,3
18,2023-06-26 09:00:00,20.8,20.8,2.2,4.4,3,38,1012.9,55,0.0,variable-cloudiness,8
19,2023-06-26 10:00:00,22.2,22.2,1.8,4.7,328,13,1012.2,46,0.0,partly-cloudy,5
20,2023-06-26 11:00:00,23.8,23.3,2.7,5.0,305,38,1011.9,40,0.0,variable-cloudiness,8
21,2023-06-26 12:00:00,20.1,20.1,2.5,4.7,10,50,1012.1,59,0.0,rain-showers,7
22,2023-06-26 13:00:00,22.6,22.6,2.3,5.2,10,13,1011.7,45,0.0,partly-cloudy,5
23,2023-06-26 14:00:00,21.3,21.3,4.3,7.2,303,88,1011.6,53,0.1,rain,1

In [17]:
#merged = merged.drop(['conditionCode'], axis = 1)
merged = merged.rename(columns = {'id': 'condition_id'})
merged = merged.rename_axis('id')
merged = merged.reset_index()
merged

,id,observationTimeUtc,airTemperature,feelsLikeTemperature,windSpeed,windGust,windDirection,cloudCover,seaLevelPressure,relativeHumidity,precipitation,condition_id
0,0,2023-06-25 15:00:00,24.5,24.0,3.2,6.4,309,75,1014.9,37,0.0,0
1,1,2023-06-25 16:00:00,20.4,20.4,4.7,9.9,318,100,1015.9,49,0.0,6
2,2,2023-06-25 17:00:00,15.8,15.8,1.8,4.2,342,100,1016.2,86,1.3,9
3,3,2023-06-25 18:00:00,16.1,16.1,3.2,6.2,303,88,1016.4,84,0.1,1
4,4,2023-06-25 19:00:00,15.6,15.6,0.9,2.0,145,100,1015.6,86,0.1,9
5,5,2023-06-25 20:00:00,14.4,14.4,0.7,1.7,234,75,1015.6,93,0.0,0
6,6,2023-06-25 21:00:00,13.5,13.5,1.4,2.2,278,0,1015.7,95,0.0,3
7,7,2023-06-25 22:00:00,12.6,12.6,0.5,0.8,329,75,1015.7,96,0.0,0
8,8,2023-06-25 23:00:00,12.5,12.5,1.5,2.5,338,63,1015.5,97,0.0,0
9,9,2023-06-26 00:00:00,12.0,12.0,0.9,1.4,331,0,1015.5,96,0.0,2
10,10,2023-06-26 01:00:00,11.4,11.4,0.5,0.7,18,0,1015.3,97,0.0,2
11,11,2023-06-26 02:00:00,10.8,10.8,0.2,0.4,105,38,1015.0,97,0.0,4
12,12,2023-06-26 03:00:00,11.1,11.1,0.8,1.1,201,38,1014.7,97,0.0,4
13,13,2023-06-26 04:00:00,14.0,14.0,1.0,1.7,97,88,1014.4,93,0.0,6
14,14,2023-06-26 05:00:00,15.6,15.6,0.8,1.5,189,88,1014.2,86,0.0,6
15,15,2023-06-26 06:00:00,15.5,15.5,1.6,2.7,86,50,1013.9,89,0.0,8
16,16,2023-06-26 07:00:00,18.2,18.2,0.9,2.3,347,25,1013.7,74,0.0,5
17,17,2023-06-26 08:00:00,20.2,20.2,1.9,3.8,8,0,1013.2,54,0.0,3
18,18,2023-06-26 09:00:00,20.8,20.8,2.2,4.4,3,38,1012.9,55,0.0,8
19,19,2023-06-26 10:00:00,22.2,22.2,1.8,4.7,328,13,1012.2,46,0.0,5
20,20,2023-06-26 11:00:00,23.8,23.3,2.7,5.0,305,38,1011.9,40,0.0,8
21,21,2023-06-26 12:00:00,20.1,20.1,2.5,4.7,10,50,1012.1,59,0.0,7
22,22,2023-06-26 13:00:00,22.6,22.6,2.3,5.2,10,13,1011.7,45,0.0,5
23,23,2023-06-26 14:00:00,21.3,21.3,4.3,7.2,303,88,1011.6,53,0.1,1

In [24]:
engine = create_engine("mysql+pymysql://root:@localhost/bootcamp")
merged.to_sql(name="weather_info",con=engine,if_exists="append",index = False)

24

In [25]:
engine = create_engine("mysql+pymysql://root:@localhost/bootcamp")

with engine.connect() as con:
    statement = text("ALTER TABLE weather_info ADD PRIMARY KEY (id);")
    con.execute(statement)

with engine.connect() as con:
    statement = text('ALTER TABLE weather_conditions ADD PRIMARY KEY (id);')
    con.execute(statement)

with engine.connect() as con:
    statement = text('ALTER TABLE weather_info ADD FOREIGN KEY (condition_id) REFERENCES weather_conditions (id);')
    con.execute(statement)

In [27]:
engine = create_engine("mysql+pymysql://root:@localhost/bootcamp")
with engine.connect() as con:
    query = 'SELECT * FROM weather_info'
    final = pd.read_sql(query, con)

final

,id,observationTimeUtc,airTemperature,feelsLikeTemperature,windSpeed,windGust,windDirection,cloudCover,seaLevelPressure,relativeHumidity,precipitation,condition_id
0,0,2023-06-25 15:00:00,24.5,24.0,3.2,6.4,309,75,1014.9,37,0.0,0
1,1,2023-06-25 16:00:00,20.4,20.4,4.7,9.9,318,100,1015.9,49,0.0,6
2,2,2023-06-25 17:00:00,15.8,15.8,1.8,4.2,342,100,1016.2,86,1.3,9
3,3,2023-06-25 18:00:00,16.1,16.1,3.2,6.2,303,88,1016.4,84,0.1,1
4,4,2023-06-25 19:00:00,15.6,15.6,0.9,2.0,145,100,1015.6,86,0.1,9
5,5,2023-06-25 20:00:00,14.4,14.4,0.7,1.7,234,75,1015.6,93,0.0,0
6,6,2023-06-25 21:00:00,13.5,13.5,1.4,2.2,278,0,1015.7,95,0.0,3
7,7,2023-06-25 22:00:00,12.6,12.6,0.5,0.8,329,75,1015.7,96,0.0,0
8,8,2023-06-25 23:00:00,12.5,12.5,1.5,2.5,338,63,1015.5,97,0.0,0
9,9,2023-06-26 00:00:00,12.0,12.0,0.9,1.4,331,0,1015.5,96,0.0,2
10,10,2023-06-26 01:00:00,11.4,11.4,0.5,0.7,18,0,1015.3,97,0.0,2
11,11,2023-06-26 02:00:00,10.8,10.8,0.2,0.4,105,38,1015.0,97,0.0,4
12,12,2023-06-26 03:00:00,11.1,11.1,0.8,1.1,201,38,1014.7,97,0.0,4
13,13,2023-06-26 04:00:00,14.0,14.0,1.0,1.7,97,88,1014.4,93,0.0,6
14,14,2023-06-26 05:00:00,15.6,15.6,0.8,1.5,189,88,1014.2,86,0.0,6
15,15,2023-06-26 06:00:00,15.5,15.5,1.6,2.7,86,50,1013.9,89,0.0,8
16,16,2023-06-26 07:00:00,18.2,18.2,0.9,2.3,347,25,1013.7,74,0.0,5
17,17,2023-06-26 08:00:00,20.2,20.2,1.9,3.8,8,0,1013.2,54,0.0,3
18,18,2023-06-26 09:00:00,20.8,20.8,2.2,4.4,3,38,1012.9,55,0.0,8
19,19,2023-06-26 10:00:00,22.2,22.2,1.8,4.7,328,13,1012.2,46,0.0,5
20,20,2023-06-26 11:00:00,23.8,23.3,2.7,5.0,305,38,1011.9,40,0.0,8
21,21,2023-06-26 12:00:00,20.1,20.1,2.5,4.7,10,50,1012.1,59,0.0,7
22,22,2023-06-26 13:00:00,22.6,22.6,2.3,5.2,10,13,1011.7,45,0.0,5
23,23,2023-06-26 14:00:00,21.3,21.3,4.3,7.2,303,88,1011.6,53,0.1,1